In [13]:
import os
import geopandas as gpd
import pandas as pd

In [2]:
os.getcwd()

'/Users/jphuong/Documents/Observatory/tutorials'

In [8]:
f22 = '/Users/jphuong/Downloads/tl_2022_01001_faces/tl_2022_01001_faces.shp'
f23 = '/Users/jphuong/Downloads/tl_2023_01001_faces/tl_2023_01001_faces.shp'

In [9]:
f22_1 = gpd.read_file(f22)
f22_1

,TFID,STATEFP20,COUNTYFP20,TRACTCE20,BLKGRPCE20,BLOCKCE20,SUFFIX1CE,ZCTA5CE20,UACE20,PUMACE20,...,METDIVFP,CNECTAFP,NECTAFP,NCTADVFP,LWFLAG,OFFSET,ATOTAL,INTPTLAT,INTPTLON,geometry
0,238788354,01,001,020501,1,1027,None,36067,58600,01700,...,None,None,None,None,L,N,1067,+32.4267500,-86.4115220,"POLYGON ((-86.41182 32.4268, -86.41137 32.4269..."
1,265282099,01,001,020501,1,1023,None,36067,58600,01700,...,None,None,None,None,L,N,785651,+32.4351124,-86.4143275,"POLYGON ((-86.41799 32.4401, -86.41742 32.4402..."
2,265281825,01,001,020902,1,1010,None,36091,None,01700,...,None,None,None,None,L,N,260,+32.7063564,-86.6076440,"POLYGON ((-86.60774 32.70633, -86.60776 32.706..."
3,265281874,01,001,020902,1,1010,None,36091,None,01700,...,None,None,None,None,L,N,31439,+32.7057861,-86.6101887,"POLYGON ((-86.61165 32.70635, -86.6085 32.7064..."
4,265281828,01,001,020902,1,1010,None,36091,None,01700,...,None,None,None,None,P,N,971,+32.7063326,-86.6080991,"POLYGON ((-86.6085 32.7064, -86.60782 32.7064,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4434,215951054,01,001,020901,2,2032,None,36022,None,01700,...,None,None,None,None,L,N,284980,+32.6103050,-86.4768449,"POLYGON ((-86.48103 32.61282, -86.4807 32.6137..."
4435,215951081,01,001,020805,2,2010,None,36022,None,01700,...,None,None,None,None,L,N,510792,+32.5803049,-86.4251689,"POLYGON ((-86.42935 32.5814, -86.4292 32.58157..."
4436,223757553,01,001,020801,1,1046,None,36067,None,01700,...,None,None,None,None,L,Y,326,+32.4208964,-86.5103888,"POLYGON ((-86.51054 32.42081, -86.51035 32.421..."
4437,223757551,01,001,020801,1,1046,None,36067,None,01700,...,None,None,None,None,L,Y,251,+32.4206881,-86.5106021,"POLYGON ((-86.51073 32.42063, -86.51054 32.420..."
4438,223757579,01,001,020801,1,1046,None,36067,None,01700,...,None,None,None,None,L,Y,3095,+32.4219613,-86.5093233,"POLYGON ((-86.51035 32.42102, -86.50966 32.421..."

In [10]:
f23_1 = gpd.read_file(f23)
f23_1

,TFID,STATEFP20,COUNTYFP20,TRACTCE20,BLKGRPCE20,BLOCKCE20,SUFFIX1CE,ZCTA5CE20,UACE20,PUMACE20,...,SLDLST,CSAFP,CBSAFP,METDIVFP,LWFLAG,OFFSET,ATOTAL,INTPTLAT,INTPTLON,geometry
0,238788354,01,001,020501,1,1027,None,36067,58600,01700,...,088,388,33860,None,L,N,1067,+32.4267500,-86.4115220,"POLYGON ((-86.41182 32.4268, -86.41137 32.4269..."
1,265282099,01,001,020501,1,1023,None,36067,58600,01700,...,088,388,33860,None,L,N,785651,+32.4351124,-86.4143275,"POLYGON ((-86.41799 32.4401, -86.41742 32.4402..."
2,265281825,01,001,020902,1,1010,None,36091,None,01700,...,042,388,33860,None,L,N,260,+32.7063564,-86.6076440,"POLYGON ((-86.60774 32.70633, -86.60776 32.706..."
3,265281874,01,001,020902,1,1010,None,36091,None,01700,...,042,388,33860,None,L,N,31439,+32.7057861,-86.6101887,"POLYGON ((-86.61165 32.70635, -86.6085 32.7064..."
4,265281828,01,001,020902,1,1010,None,36091,None,01700,...,042,388,33860,None,P,N,971,+32.7063326,-86.6080991,"POLYGON ((-86.6085 32.7064, -86.60782 32.7064,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4434,215951054,01,001,020901,2,2032,None,36022,None,01700,...,042,388,33860,None,L,N,284980,+32.6103050,-86.4768449,"POLYGON ((-86.48103 32.61282, -86.4807 32.6137..."
4435,215951081,01,001,020805,2,2010,None,36022,None,01700,...,042,388,33860,None,L,N,510792,+32.5803049,-86.4251689,"POLYGON ((-86.42935 32.5814, -86.4292 32.58157..."
4436,223757553,01,001,020801,1,1046,None,36067,None,01700,...,069,388,33860,None,L,Y,326,+32.4208964,-86.5103888,"POLYGON ((-86.51054 32.42081, -86.51035 32.421..."
4437,223757551,01,001,020801,1,1046,None,36067,None,01700,...,069,388,33860,None,L,Y,251,+32.4206881,-86.5106021,"POLYGON ((-86.51073 32.42063, -86.51054 32.420..."
4438,223757579,01,001,020801,1,1046,None,36067,None,01700,...,069,388,33860,None,L,Y,3095,+32.4219613,-86.5093233,"POLYGON ((-86.51035 32.42102, -86.50966 32.421..."

In [29]:
f22_1.crs, f23_1.crs

(<Geographic 2D CRS: EPSG:4269>
 Name: NAD83
 Axis Info [ellipsoidal]:
 - Lat[north]: Geodetic latitude (degree)
 - Lon[east]: Geodetic longitude (degree)
 Area of Use:
 - name: North America - onshore and offshore: Canada - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon. Puerto Rico. United States (USA) - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Hawaii; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands. British Virgin Islands.
 - bounds: (167.65, 14.92, -40.73, 86.45)
 Datum: North American Datum 1983
 - Ellipsoid: GRS 1980
 - Prime Meridian: Greenwich,
 <Geographic 2D CRS: EPSG:4269>
 Name: NAD83
 Axis Info [ellipsoidal]:
 - Lat[north]: Geodetic latitude (degree)
 - Lon[east]: Geodetic longitude (degree)
 Area of Use:
 - name: North America - onshore and offshore: Canada - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon. Puerto Rico. United States (USA) - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Hawaii; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands. British Virgin Islands.
 - bounds: (167.65, 14.92, -40.73, 86.45)
 Datum: North American Datum 1983
 - Ellipsoid: GRS 1980
 - Prime Meridian: Greenwich)

In [16]:
f22_1.dtypes

TFID             int64
STATEFP20       object
COUNTYFP20      object
TRACTCE20       object
BLKGRPCE20      object
BLOCKCE20       object
SUFFIX1CE       object
ZCTA5CE20       object
UACE20          object
PUMACE20        object
STATEFP         object
COUNTYFP        object
TRACTCE         object
BLKGRPCE        object
COUSUBFP        object
SUBMCDFP        object
ESTATEFP        object
CONCTYFP        object
PLACEFP         object
AIANNHFP        object
AIANNHCE        object
COMPTYP         object
TRSUBFP         object
TRSUBCE         object
ANRCFP          object
TTRACTCE        object
TBLKGPCE        object
ELSDLEA         object
SCSDLEA         object
UNSDLEA         object
SDADMLEA        object
CD118FP         object
SLDUST          object
SLDLST          object
CSAFP           object
CBSAFP          object
METDIVFP        object
CNECTAFP        object
NECTAFP         object
NCTADVFP        object
LWFLAG          object
OFFSET          object
ATOTAL           int64
INTPTLAT        object
INTPTLON        object
geometry      geometry
dtype: object

In [26]:
tmp = pd.DataFrame.from_dict(f22_1.dtypes)
tmp.columns= ['C2022']
tmp1 = tmp.copy()

tmp = pd.DataFrame.from_dict(f23_1.dtypes)
tmp.columns= ['C2023']

tmp.head()

             C2023
TFID         int64
STATEFP20   object
COUNTYFP20  object
TRACTCE20   object
BLKGRPCE20  object

In [27]:
tmp1 = pd.concat([tmp1, tmp], axis=1)
tmp1

               C2022     C2023
TFID           int64     int64
STATEFP20     object    object
COUNTYFP20    object    object
TRACTCE20     object    object
BLKGRPCE20    object    object
BLOCKCE20     object    object
SUFFIX1CE     object    object
ZCTA5CE20     object    object
UACE20        object    object
PUMACE20      object    object
STATEFP       object    object
COUNTYFP      object    object
TRACTCE       object    object
BLKGRPCE      object    object
COUSUBFP      object    object
SUBMCDFP      object    object
ESTATEFP      object    object
CONCTYFP      object    object
PLACEFP       object    object
AIANNHFP      object    object
AIANNHCE      object    object
COMPTYP       object    object
TRSUBFP       object    object
TRSUBCE       object    object
ANRCFP        object    object
TTRACTCE      object    object
TBLKGPCE      object    object
ELSDLEA       object    object
SCSDLEA       object    object
UNSDLEA       object    object
SDADMLEA      object    object
CD118FP       object    object
SLDUST        object    object
SLDLST        object    object
CSAFP         object    object
CBSAFP        object    object
METDIVFP      object    object
CNECTAFP      object       NaN
NECTAFP       object       NaN
NCTADVFP      object       NaN
LWFLAG        object    object
OFFSET        object    object
ATOTAL         int64     int64
INTPTLAT      object    object
INTPTLON      object    object
geometry    geometry  geometry

In [28]:
tmp1.loc[tmp1.apply(lambda x: x['C2022']!=x['C2023'], axis=1),:]

           C2022 C2023
CNECTAFP  object   NaN
NECTAFP   object   NaN
NCTADVFP  object   NaN