In [2]:
import os
import geopandas as gpd
import pandas as pd

In [3]:
import netCDF4 as nc
import xarray as xr

In [4]:
os.getcwd()

'/Users/jphuong/Observatory/tutorials'

In [6]:
root_dir = '/Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015'

# zip files in root
zipf = [f for f in os.listdir(root_dir) if f.endswith('.zip')]

# folders in root
fold = [f for f in os.listdir(root_dir) if not f.endswith('.zip') and ('.' not in f)]

fold

['1f34aeeee050084abd5eb16b010f8c5b',
 'f294553b45c604483ac76e0ead287015',
 '55779745d3fd682f6f077107164015a7',
 'd7f8a1c12c7c27547651dc84e57bd88d',
 '5e53c89f63764ce3aadc278055bb20b8',
 'd41b75597d2b82e13bc7ef098844c4e1',
 'f9a9ce4e7e651dec0c0a0ea464a38fd7',
 '405fceb039ee4dfde36e51877a4b0acb',
 'f3ce70097c6e04436323be98bd989c66',
 'ee251320396791049aefe7f121584de7',
 '232dda8a1d478388ff6cc692a5f91450',
 '70d4a35d07735d4a13b5eb03d8912128',
 '1ee0190cda63d83b8a0567e0661dae1',
 '94944ab1a078ba4d758d276e8a3a65f1',
 '68c446059bb7a93c8cb5ce97861f188e',
 '60eb22a84f38c867ccd46f7dd557ee31',
 '71d670a44cccb8de106fcbec575c2b9c',
 '2d6a5b32e87a0b4ba5a12bc3dac09def',
 '47df47f114de4d4a81887c9956c35c04',
 'fd7127672ae45d0bb499501eccb189c0',
 '3e6fa027938affd375f5ea3417492e8f',
 '139b33662c4ec7ae8986dac3683a4319',
 '376c798edf780c93cdef2e62a2822c33',
 '4a1fca3f6176e0c7438b64a7e4443370',
 '729a0783cc9bcaa137283f7d5b628b34',
 'f8f458e87c50d99348907ddf00579507',
 '7a627b344c80d50e7fae5d5bf7c1ccf4',
 '7bded2c80384940d794b3bac99a73f64',
 '54221e544f3e28dc59a1844adef0ceb5',
 '22dbe50d50ec86de6a7a334edf538ea6',
 '56601f3ad272c17d14d2345da5a14827',
 '8416e27e983c9730cfaf314932f45b51',
 '516cd092802a79d587786d72240dcfca',
 '11e2ae5fbd5137dbd09139c969c2d2b',
 '34ab5cddddf5e680fc05906a4166f559',
 '717c4b97a85ecc4b9347143bd44842d7',
 'ba92a9b681e5416b92d009ff8e381afa',
 '4b47007cd121324d863a293c0053618a',
 '21c1ef18a707dc386b375c1e57284e2a',
 'f1c648ec9b409b1f0b377f6ecba97b2f',
 '8b84bb89f85000531b1dbdcedd140a45',
 'f8071feca2829af90b25d1b26848e3dc',
 '13e2f62cd348912b1216a89f96582fb6',
 '3aa972d3bf5d4342b5f7b54e50a07acc',
 '1a85a309f5bf7d7e74b14a369c7b2925',
 'ef5c73009c2abab9a47c52be0972c108',
 '5fc72924f3660cbe00ef2dd159083ebc',
 '8d42e199a297c1c749a584a22e3f4ab8',
 '2718cefdd5ecc4fcdfec36d95d973c50',
 '72b57fbe0c511cc316172b8f697c4642',
 'bd3536850e49815bfeb96fdc553f369b',
 '19fa232587c5238c2be492cd0ea1f89',
 '4613934966574a19c26d3233ae3c5ba6',
 'd506884013146a4f463da4ed8ce2b61a',
 '413defce2f2c5304442d68148e2977fc',
 '85c19c5e436590ad4beb6ddba948bb44',
 'c72e7b5bb50399a2e603843355266da6',
 '1be6c1b11b7ece0dbc74fd6bed3bae62',
 '76d94fbe397b7aa14f0a05c5a7dc40db',
 'da6746464e3869ffe6b773657591161e',
 'a909eb6cdc19d1dc6192b0f5932394a8',
 '31c814b5094c42dc600ebc1afaf3aec4',
 'dddcd94b0ecfb563529a1b265e690fef',
 '7b1ab2b028395728b7ce092344f967d3',
 '2566bcaac078ee1fc6f1744e42219bc3',
 '61f29aade065cc860f5f74078bf3e405',
 '9b1e6029e827f7bb02bf0d938ce9cf1b',
 'e92472d785f4a3d9fbddc8e10bcf6a0c',
 'ccd05b4af90b75dcd1d489585c067804',
 'cbe7092d023bf588d0537d9e060e3e4',
 'c5b9c76a44e974d9bedb47a1126e60f3',
 '7914aefbbe5ace32025bb19a5cf06a94',
 'f82b3edcb9b82a08d21202e44ccb40cf',
 '2a7c0293e5d2f0503a70f11d0559205f',
 'eb7473aa3f8fe7d77511903984043835',
 'c0eb0eedeab11a76bd0dcd252c375afd',
 '3eee3b70d6a7153db9f7146e74a43423',
 '34605eadab57f98ab94fe78b00d762d3',
 '816f72f2d74e5c0f2d469f15a87107e',
 '7f2d354f79b97b0b4246922f5f84e5f7',
 '6ec2191a2fdb883bbc834971c3a230cb',
 'e98cad99b03352857a0875dc01df3b5e',
 'ab9add7fd96cc7b33f3c8036daec422d',
 '49ad7d077b98d2f3d0623bd59a48c97a',
 '3f20334c3b4018200829e21cc3b8ea24',
 '403a9b38cca21e57d432d64644feb21c',
 '69190d0d97cd242b0dffae77b006a389',
 '8db58eee4b9342a4b4798f88eae794b7',
 '11d660c145d2a94f66660e405fe71709',
 'a3fc04b3f04f709c3fac892d5817e2ee',
 'c276b6dc2a03cddbefa93756c1f8e832',
 'a9fd8abfa741cd7ab7b01032bdf01928',
 '3b516a099e9265093a13a2f6d09c4b6',
 '645aec3af8a565a1ce76196580305653',
 'c2b6f5f7999ef55981278fb934306662',
 '202b9ba6d74f412a82d87834bc18dd47',
 '2211e2758c9e132bb4175cbe6bf2caba',
 '8b051dcb81541511b6a0f7fe136c3f54',
 'bd13055d02865ac2ced1298e286caba5',
 '77645e5a04107ad5f3db7cefaf59dbd5',
 '36946788df37e79fda1c89812eaa91d1',
 'e2f82f19d4a07d2dc676ac26243710c',
 '14e0052bd31697449a75bf2283e43508',
 '9ff2f1d582033c025e2dab8b9e1c6aac',
 'b9ee674b86c15e0efa1917aaaf3d7e98',
 '290900c0a93aaab2e3cd718b9d9b94f1',
 '646febd7f2d8edbf034c280b53b4758',
 'a4b6082afa5415bc7da7e72a22ab6fc9',
 'd7302fa9308fb73306fd880410b0b027',
 '6f31cb580f4410c5190114821c965d63',
 'ed5929856875acf96374e7af084b7b89',
 '4988ed7652377d13e31eba9bc6ea578',
 '8e2db044c642db140d76cf086252a930',
 '4569d960535dbfd697a38235c2eeccc6',
 'a87d77e141b0afc2a8be298c1405ce97',
 '93008cd63480b12f912a45063c92fcea',
 '3e139ce96849f8e76d53fa229a81bbbe',
 'c518711bf7c310e778f8025ef6ff2973',
 '38e2b97322ee453637b71da7b9d4dba8',
 'f08ee6e4e5b863508c5bf60359053120',
 '292c6bb22290ceb11c1c82d1d6111d36',
 'acde1fd1b674f699d6f4ef199a9ce347',
 '40eeffbb68222d9e3a7098cdd18f8879',
 'f683dc3160bc6be5800679e5d6760646',
 'e115d097d7ff6a107fe1e2e32c74881d',
 'e2f1f662c446e88924abc95143e92b0a',
 'd7b58eb366ee247dfafe1b58fba40525',
 'e81a85b19b9b0e52ee09fba8e58b8d99',
 '67f46876ccb48a0b4462ddb062a56250',
 '856dce35557af051d6a11d09eb49bbc7',
 '7a4f7d8c3b9aa1f0798ea36d14d61e22',
 'b6b6e9032eef58c20b3ef1868f1ce40',
 'ba8e745478de3435bcdbb1759891fbf6',
 '95f7a909e6f53e0628a56ecc4ec92d13',
 '461db950594f9c6dfbdafbae33284ae',
 'a83bd568d95664318703f24a3ae418ba',
 'd2cf82bfcf0e5199a66a47c9826e7356',
 'bedc5edc27b3e2ae33530146a67a18d9',
 'b97d075bdb2e45cb0a2820fd55c40b8f',
 'fff35e77040a1508d17d58f236c35e4b',
 '3bc5bedfd3b63a3d67286f8cd3cc49b5',
 '89cc78783cada5d37c54874eead08397',
 '647af0b3b60b7e0c8e79f4767ea763c0',
 'ecb738b2095981db44bd0a9c75b9479f',
 'd2b4ca4bb253a600546f32ecbab23fee',
 'b7a8ef3417f453cbd1d1e287532b130a',
 '1b794351f748c67d9903c518228e6abd',
 'fee3ac2a69e002488cc25d23114b0ad',
 '3685653b305a2670a3076101d80f68e1',
 'ac10637cb5613a8b160adc696581ac46',
 'c1ea208cc385c3d97289dc0457c357fb',
 'a1aef3462a02a2d7a94fc372159f3a2',
 'a09ba0fff28945d46f71684b15c68f82',
 'c03883c16106673a1692d11a58cc6e4e',
 '21f14bbf4200fb890ba103e0cebe2d0a',
 '838ab7a7ce7fce818aa6b810814c1cec',
 '6847ac0fd53495c9aa48e7a7097a7c4e',
 '5ed07d54714481e6a073fe829f727f3a',
 'df5064da07e45088c99835fb1512d515',
 'cf14186fda7b6faac4ba596a770cfdf5',
 '5de42b8c2bb7b8acdf3d051d943fb8df',
 'de7b01128082013a2f347cbe3ab7a843',
 'e7e870a0a689f991f870ae45a847badf',
 'e590bfc9cdd893f6a73f256c039079ee',
 '2177afbfd023258db22d4f1587d8001',
 'f82f4d89b23e519f3522c552fc2bf06e',
 '3a1095affa3d8a135599777af2b7005a',
 'ff91be1709bee31ad754aa1f0d49e3f3',
 '19a1e8764dc0076f6e8502c0afe4c567',
 '5c2ac5510c05d4dedf3eda3231509e4a',
 '5a312605bc978a001c74c6f16b751f8a',
 'cc66ce2dfe1d9097c9e899b57d298b2c',
 '523632e0c2385b1aeb06965844c9b955',
 '8ee3d7a474383b736416b73664acc999',
 '23b76a43b3c670d733dd1ce31d6c6f20',
 '40502e676682d22fc627910037e68276',
 '656ed160baa9e46affa1bd0506009e1c',
 'c5d865e3213ff224bc04b7f7b5928c8e',
 '1a5a5ff661ee7b72683365e00e3bbc25',
 'ebc216f958ecfef8b6e5bed4770a3a79',
 '6b8083d4232e6bc0b3c53c9fa5bb9d6e',
 '29efa957998210d634e73102e97d3bc2',
 '5d3e93f534c8058921600ef14da55d11',
 '93143081fdc1997fcf71eedb48bb23c4',
 'd0e9c3576f0d978fb58bd7725f655e31',
 '6b8fa8bb7118ac7b5a901404eb3110d3',
 '2cdb5c95ce7c71655d26ed02438ccc3',
 '360d0b0d0bf1a8112f9bee04350ac44b',
 '9a396d5e80801c6963f2da7644cabb9b',
 'f46b988ce96cd7de25cbad6119a8ac50',
 'f0bbccf84b9c6ac768bb110b89974334',
 'e2ea96994574cac98edd333c13598c46',
 'b7e1efbf5371111618be79d6c12a574e',
 'COPIES',
 'a3741a0727e095a6a2007c47a402b61e',
 '232e87e239e93bdb49671e244db5f6d0',
 '5f10fbdecb676febad3c3f1d9ddab6e4',
 '6ec737bb3d26643629c37694bd57bfa9',
 'a8d13210c76f7a7a6cb3764b56f397e9',
 '1098f09a3aa1e3488765242d53ebf436',
 'd4d1076e270f84cc38fcce80acbca4ab',
 'ce9d3800727efd526f743c14b4506ffe',
 'ed75ec9e1645aec7e68cdede0d83acce',
 '97aa55374e2d6cc98614bb74ff8cba8e',
 'd79047de1408527efeca9bc00259d92c',
 'f116864d9c1e65b014002d787b71be17',
 'a0572f48e774b09b65ffd40f37135b51',
 '825dbc676dbd0b3370e0c7719a63a425',
 '701d8c8f63a6f249d0fb2554efc94686',
 '7cf17bd7f749682003635ee9135ab832',
 'a22af0bb1ed1e47f9f285f7f6a766d6',
 'dc5a479bafd3f74020a241662175b57d',
 '7f28b14639e1b9ca197e08dca4bf4e3',
 '50996a518d7453801fbc2288b26bcd69',
 'c65e07ec3d9c631a4b5e268b9d5d5009',
 '46d50398dc9b8dba907eb4a2699e388f',
 'b549dc815a1841ae4db2112c809a9689',
 'e2a7883609fd42bdc9d6a56af23db50f',
 'bae93ebef76efa36f03f0f641573c060',
 '9f9778f0155ce7027e26de2a076ee6f5',
 'fbfea65ab63343fbeeca4f1199e6e0e0',
 'eb3855d4ad37bd06d454977da4897eb4',
 '71272abcf165535abed0bd595b0e9b63',
 'ca4b233183b3a8119d721eaa6d699d6a',
 '1b2910fba3d00922c80c8c3f0c1b721e',
 '140cb04099c769d03cb90ec25e45f88',
 'c6ad6a84d2788eb5b07a37a0684ef6e7',
 'b8dc3e68f8449b1da7e37e00b3f9f4fe',
 'c8203a41c64794261cf09ee68c1f2940',
 '71cd609ade447c8828c1f3218b69bda7',
 '37e13adb975930781fe9b69cd1206f43',
 '36f2e0ccc04f257f2b68bd3b6126e52c',
 '37db4e97ba8b9883f7bee6a5509d6de4',
 '297cf189d4ce1deb72cba1127038e5d1',
 '25809bf822af0616ed596b73ea7fbf8c',
 '4a09800fac28b5b0262fdabd678d7898',
 'f2c27efb9dff3cfcfd46bff4a3b09746',
 'a53d195bde06b39edf10ed4e5b5bed23',
 'bd630f8e35d9e3f9ddef492c02ba182',
 '99d929a3dbaec5cfab585347844c524d',
 'c59bd41ec54b844fe847d4f6e34b342c',
 'a7db49f472ebbfaa4ed9320fd882cd12',
 '93dfed1b00e51cdf8b8a97a7e593b740',
 '8401179da97b9cd0ce31f7013160c998',
 'bb6836c790e84c9575cd53b0c3272f68',
 'b313a7f46c89a4cae0b8ec8293c6e944',
 '366a9b110abb099081ed7363b41829c2',
 '5bf938c26fd17d608c07ca6ccabb2b0b',
 '521e7057b110eaedf6073ef4d15a667a',
 '6eab4042f4551f860ff05480818ac23b',
 '2b60501e90f9314addaa87bbbb8345fd',
 '10a49809e53fcae0233beb77036d15f7',
 '813d3b44cd75e28f3ad3ed591f5ab915',
 'aed3fb9593cd6b60d68e6527dee8e3f3',
 '8c2ad6ffec9759b78fd469369821b635',
 'f64394782c2c9f46ec37c5976bf3eada',
 'ccadabd579e8d6b0d870da18fa015b8d',
 '87a598e2f229366b9f425abe6dcf1093',
 '731846c5b168415a1298071c252381a4',
 'aceea1750b1fcabb624df577fdc9fdad',
 '16895cf981140a0c7b9c6228a060cb68',
 'ac1245caad53434add31917ab35c83fa',
 '765dbaa3a592d3af3e7d0a0feac0e7d5',
 '26f176fd3f6b6cccbb1e2acc38a68f3d',
 '283b82dd8720eb4df55e354716c4e3ac',
 '33ccb3b996ba28909eb3df5dd6bab261',
 'ca7d31570e0c293156359cfb8c2b6c1a',
 'f811851e5d1ef86c8cf33e3190625f13',
 'b7759ffafed67861a19bf5e39ff8df45',
 'cb16a11ba6d565d67c1b53d052ed69a2',
 'de805e86dfd4a31a19695f5b3b01f519',
 '82181c4d41b17ced08f8be15f490b553',
 '16f8186eb2af8a6298d78dc35908828e',
 'ccac7358fb921ec75b0b50c7f14eeb38',
 'de5777767d1db255b17d54c3b7c021ba',
 '158a58aa08f9ba03d53868c3b2f9a8aa',
 '75a78c7946f25b541eadd7aacf701feb',
 'ec5d2e46cd9950ded3c89ff1f57d5688',
 'd09fc261467bb3a618981dbf9bdd1f7e',
 '3d08bf275a2849585b9e2b86b3c659ec',
 '87293f160c7873a93d064a0aa68e4889',
 '1473938558d42fc6ea10cf62e4eb3ccb',
 'd14b2187872b7c4ac45108be2f23ffd5',
 '4841b524cedac7ff774de4a7650fd463',
 'd661a4fc9372af3edc85235e496946c7',
 '2ba013ed8a9aa7e5091a40d8b17ee097',
 '17b4b5a9cbdb58ff462ba607dab0bd43',
 '93210142c63fcf587f17a562712cfea0',
 'cf1bb6782d12f870dc1f496122aede20']

## 2) Unzip the remaining zipfiles

In [7]:
import zipfile

def unzip_file_path (zip_path):
    """
    function to unzip all the zip files

    zip_path (dir): path to the zip file

    return: unzipped folder by the same name with the contents within
    """
    # start
    print('starting: {0}'.format(zip_path))

    # extract
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(os.path.join(root_dir, zip_path.replace('.zip','')))

    # stop
    print('done: {0}'.format(zip_path))

In [8]:
os.path.join(root_dir, zipf[0])

'/Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/1b794351f748c67d9903c518228e6abd.zip'

In [9]:
%%time

# iterate through each file
for ind, f in enumerate(zipf):
    print(ind+1)

    unzip_file_path(os.path.join(root_dir, f))

1
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/1b794351f748c67d9903c518228e6abd.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/1b794351f748c67d9903c518228e6abd.zip
2
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6847ac0fd53495c9aa48e7a7097a7c4e.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6847ac0fd53495c9aa48e7a7097a7c4e.zip
3
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/dddcd94b0ecfb563529a1b265e690fef.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/dddcd94b0ecfb563529a1b265e690fef.zip
4
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/e2f82f19d4a07d2dc676ac26243710c.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/e2f82f19d4a07d2dc676ac26243710c.zip
5
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/82181c4d41b17ced08f8be15f490b553.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/82181c4d41b17ced08f8be15f490b553.zip
6
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/7a627b344c80d50e7fae5d5bf7c1ccf4.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/7a627b344c80d50e7fae5d5bf7c1ccf4.zip
7
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/25809bf822af0616ed596b73ea7fbf8c.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/25809bf822af0616ed596b73ea7fbf8c.zip
8
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/ed75ec9e1645aec7e68cdede0d83acce.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/ed75ec9e1645aec7e68cdede0d83acce.zip
9
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/232dda8a1d478388ff6cc692a5f91450.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/232dda8a1d478388ff6cc692a5f91450.zip
10
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f46b988ce96cd7de25cbad6119a8ac50.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f46b988ce96cd7de25cbad6119a8ac50.zip
11
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/d2b4ca4bb253a600546f32ecbab23fee.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/d2b4ca4bb253a600546f32ecbab23fee.zip
12
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/4b47007cd121324d863a293c0053618a.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/4b47007cd121324d863a293c0053618a.zip
13
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/bae93ebef76efa36f03f0f641573c060.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/bae93ebef76efa36f03f0f641573c060.zip
14
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/647af0b3b60b7e0c8e79f4767ea763c0.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/647af0b3b60b7e0c8e79f4767ea763c0.zip
15
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/85c19c5e436590ad4beb6ddba948bb44.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/85c19c5e436590ad4beb6ddba948bb44.zip
16
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/d79047de1408527efeca9bc00259d92c.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/d79047de1408527efeca9bc00259d92c.zip
17
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/55779745d3fd682f6f077107164015a7.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/55779745d3fd682f6f077107164015a7.zip
18
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/5ed07d54714481e6a073fe829f727f3a.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/5ed07d54714481e6a073fe829f727f3a.zip
19
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c0eb0eedeab11a76bd0dcd252c375afd.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c0eb0eedeab11a76bd0dcd252c375afd.zip
20
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/b8dc3e68f8449b1da7e37e00b3f9f4fe.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/b8dc3e68f8449b1da7e37e00b3f9f4fe.zip
21
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/bedc5edc27b3e2ae33530146a67a18d9.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/bedc5edc27b3e2ae33530146a67a18d9.zip
22
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/a87d77e141b0afc2a8be298c1405ce97.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/a87d77e141b0afc2a8be298c1405ce97.zip
23
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/729a0783cc9bcaa137283f7d5b628b34.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/729a0783cc9bcaa137283f7d5b628b34.zip
24
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/3b516a099e9265093a13a2f6d09c4b6.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/3b516a099e9265093a13a2f6d09c4b6.zip
25
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/2d6a5b32e87a0b4ba5a12bc3dac09def.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/2d6a5b32e87a0b4ba5a12bc3dac09def.zip
26
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/dc5a479bafd3f74020a241662175b57d.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/dc5a479bafd3f74020a241662175b57d.zip
27
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/717c4b97a85ecc4b9347143bd44842d7.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/717c4b97a85ecc4b9347143bd44842d7.zip
28
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/50996a518d7453801fbc2288b26bcd69.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/50996a518d7453801fbc2288b26bcd69.zip
29
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/11e2ae5fbd5137dbd09139c969c2d2b.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/11e2ae5fbd5137dbd09139c969c2d2b.zip
30
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c59bd41ec54b844fe847d4f6e34b342c.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c59bd41ec54b844fe847d4f6e34b342c.zip
31
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/14e0052bd31697449a75bf2283e43508.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/14e0052bd31697449a75bf2283e43508.zip
32
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/cf14186fda7b6faac4ba596a770cfdf5.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/cf14186fda7b6faac4ba596a770cfdf5.zip
33
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f8f458e87c50d99348907ddf00579507.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f8f458e87c50d99348907ddf00579507.zip
34
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/521e7057b110eaedf6073ef4d15a667a.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/521e7057b110eaedf6073ef4d15a667a.zip
35
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/36f2e0ccc04f257f2b68bd3b6126e52c.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/36f2e0ccc04f257f2b68bd3b6126e52c.zip
36
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/eb7473aa3f8fe7d77511903984043835.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/eb7473aa3f8fe7d77511903984043835.zip
37
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/3d08bf275a2849585b9e2b86b3c659ec.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/3d08bf275a2849585b9e2b86b3c659ec.zip
38
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/a09ba0fff28945d46f71684b15c68f82.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/a09ba0fff28945d46f71684b15c68f82.zip
39
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/54221e544f3e28dc59a1844adef0ceb5.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/54221e544f3e28dc59a1844adef0ceb5.zip
40
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/7f2d354f79b97b0b4246922f5f84e5f7.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/7f2d354f79b97b0b4246922f5f84e5f7.zip
41
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/413defce2f2c5304442d68148e2977fc.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/413defce2f2c5304442d68148e2977fc.zip
42
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/68c446059bb7a93c8cb5ce97861f188e.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/68c446059bb7a93c8cb5ce97861f188e.zip
43
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/523632e0c2385b1aeb06965844c9b955.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/523632e0c2385b1aeb06965844c9b955.zip
44
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/856dce35557af051d6a11d09eb49bbc7.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/856dce35557af051d6a11d09eb49bbc7.zip
45
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c6ad6a84d2788eb5b07a37a0684ef6e7.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c6ad6a84d2788eb5b07a37a0684ef6e7.zip
46
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/9b1e6029e827f7bb02bf0d938ce9cf1b.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/9b1e6029e827f7bb02bf0d938ce9cf1b.zip
47
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/61f29aade065cc860f5f74078bf3e405.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/61f29aade065cc860f5f74078bf3e405.zip
48
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/1f34aeeee050084abd5eb16b010f8c5b.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/1f34aeeee050084abd5eb16b010f8c5b.zip
49
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/765dbaa3a592d3af3e7d0a0feac0e7d5.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/765dbaa3a592d3af3e7d0a0feac0e7d5.zip
50
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/bb6836c790e84c9575cd53b0c3272f68.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/bb6836c790e84c9575cd53b0c3272f68.zip
51
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/b6b6e9032eef58c20b3ef1868f1ce40.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/b6b6e9032eef58c20b3ef1868f1ce40.zip
52
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f64394782c2c9f46ec37c5976bf3eada.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f64394782c2c9f46ec37c5976bf3eada.zip
53
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/5bf938c26fd17d608c07ca6ccabb2b0b.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/5bf938c26fd17d608c07ca6ccabb2b0b.zip
54
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/2b60501e90f9314addaa87bbbb8345fd.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/2b60501e90f9314addaa87bbbb8345fd.zip
55
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/fff35e77040a1508d17d58f236c35e4b.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/fff35e77040a1508d17d58f236c35e4b.zip
56
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/ccd05b4af90b75dcd1d489585c067804.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/ccd05b4af90b75dcd1d489585c067804.zip
57
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/5f10fbdecb676febad3c3f1d9ddab6e4.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/5f10fbdecb676febad3c3f1d9ddab6e4.zip
58
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/813d3b44cd75e28f3ad3ed591f5ab915.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/813d3b44cd75e28f3ad3ed591f5ab915.zip
59
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f3ce70097c6e04436323be98bd989c66.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f3ce70097c6e04436323be98bd989c66.zip
60
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/16f8186eb2af8a6298d78dc35908828e.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/16f8186eb2af8a6298d78dc35908828e.zip
61
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f8071feca2829af90b25d1b26848e3dc.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f8071feca2829af90b25d1b26848e3dc.zip
62
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6b8fa8bb7118ac7b5a901404eb3110d3.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6b8fa8bb7118ac7b5a901404eb3110d3.zip
63
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/89cc78783cada5d37c54874eead08397.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/89cc78783cada5d37c54874eead08397.zip
64
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/292c6bb22290ceb11c1c82d1d6111d36.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/292c6bb22290ceb11c1c82d1d6111d36.zip
65
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/d0e9c3576f0d978fb58bd7725f655e31.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/d0e9c3576f0d978fb58bd7725f655e31.zip
66
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c1ea208cc385c3d97289dc0457c357fb.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/c1ea208cc385c3d97289dc0457c357fb.zip
67
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/46d50398dc9b8dba907eb4a2699e388f.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/46d50398dc9b8dba907eb4a2699e388f.zip
68
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/b7a8ef3417f453cbd1d1e287532b130a.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/b7a8ef3417f453cbd1d1e287532b130a.zip
69
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/49ad7d077b98d2f3d0623bd59a48c97a.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/49ad7d077b98d2f3d0623bd59a48c97a.zip
70
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/8c2ad6ffec9759b78fd469369821b635.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/8c2ad6ffec9759b78fd469369821b635.zip
71
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/816f72f2d74e5c0f2d469f15a87107e.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/816f72f2d74e5c0f2d469f15a87107e.zip
72
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f9a9ce4e7e651dec0c0a0ea464a38fd7.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/f9a9ce4e7e651dec0c0a0ea464a38fd7.zip
73
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6ec737bb3d26643629c37694bd57bfa9.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6ec737bb3d26643629c37694bd57bfa9.zip
74
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/56601f3ad272c17d14d2345da5a14827.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/56601f3ad272c17d14d2345da5a14827.zip
75
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/a7db49f472ebbfaa4ed9320fd882cd12.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/a7db49f472ebbfaa4ed9320fd882cd12.zip
76
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6ec2191a2fdb883bbc834971c3a230cb.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/6ec2191a2fdb883bbc834971c3a230cb.zip
77
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/fee3ac2a69e002488cc25d23114b0ad.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/fee3ac2a69e002488cc25d23114b0ad.zip
78
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/94944ab1a078ba4d758d276e8a3a65f1.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/94944ab1a078ba4d758d276e8a3a65f1.zip
79
starting: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/8401179da97b9cd0ce31f7013160c998.zip
done: /Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/8401179da97b9cd0ce31f7013160c998.zip
80

In [10]:
"""
regenerate the path lists
"""

# zip files in root
zipf = [f for f in os.listdir(root_dir) if f.endswith('.zip')]

# folders in root
fold = [f for f in os.listdir(root_dir) if not f.endswith('.zip') and ('.' not in f) and ('COPIES' not in f)]

fold

['1f34aeeee050084abd5eb16b010f8c5b',
 'f294553b45c604483ac76e0ead287015',
 '55779745d3fd682f6f077107164015a7',
 'd7f8a1c12c7c27547651dc84e57bd88d',
 '5e53c89f63764ce3aadc278055bb20b8',
 'd41b75597d2b82e13bc7ef098844c4e1',
 'f9a9ce4e7e651dec0c0a0ea464a38fd7',
 '405fceb039ee4dfde36e51877a4b0acb',
 'f3ce70097c6e04436323be98bd989c66',
 'ee251320396791049aefe7f121584de7',
 '232dda8a1d478388ff6cc692a5f91450',
 '70d4a35d07735d4a13b5eb03d8912128',
 '1ee0190cda63d83b8a0567e0661dae1',
 '94944ab1a078ba4d758d276e8a3a65f1',
 '68c446059bb7a93c8cb5ce97861f188e',
 '60eb22a84f38c867ccd46f7dd557ee31',
 '71d670a44cccb8de106fcbec575c2b9c',
 '2d6a5b32e87a0b4ba5a12bc3dac09def',
 '47df47f114de4d4a81887c9956c35c04',
 'fd7127672ae45d0bb499501eccb189c0',
 '3e6fa027938affd375f5ea3417492e8f',
 '139b33662c4ec7ae8986dac3683a4319',
 '376c798edf780c93cdef2e62a2822c33',
 '4a1fca3f6176e0c7438b64a7e4443370',
 '729a0783cc9bcaa137283f7d5b628b34',
 'f8f458e87c50d99348907ddf00579507',
 '7a627b344c80d50e7fae5d5bf7c1ccf4',
 '7bded2c80384940d794b3bac99a73f64',
 '54221e544f3e28dc59a1844adef0ceb5',
 '22dbe50d50ec86de6a7a334edf538ea6',
 '56601f3ad272c17d14d2345da5a14827',
 '8416e27e983c9730cfaf314932f45b51',
 '516cd092802a79d587786d72240dcfca',
 '11e2ae5fbd5137dbd09139c969c2d2b',
 '34ab5cddddf5e680fc05906a4166f559',
 '717c4b97a85ecc4b9347143bd44842d7',
 'ba92a9b681e5416b92d009ff8e381afa',
 '4b47007cd121324d863a293c0053618a',
 '21c1ef18a707dc386b375c1e57284e2a',
 'f1c648ec9b409b1f0b377f6ecba97b2f',
 '8b84bb89f85000531b1dbdcedd140a45',
 'f8071feca2829af90b25d1b26848e3dc',
 '13e2f62cd348912b1216a89f96582fb6',
 '3aa972d3bf5d4342b5f7b54e50a07acc',
 '1a85a309f5bf7d7e74b14a369c7b2925',
 'ef5c73009c2abab9a47c52be0972c108',
 '5fc72924f3660cbe00ef2dd159083ebc',
 '8d42e199a297c1c749a584a22e3f4ab8',
 '2718cefdd5ecc4fcdfec36d95d973c50',
 '72b57fbe0c511cc316172b8f697c4642',
 'bd3536850e49815bfeb96fdc553f369b',
 '19fa232587c5238c2be492cd0ea1f89',
 '4613934966574a19c26d3233ae3c5ba6',
 'd506884013146a4f463da4ed8ce2b61a',
 '413defce2f2c5304442d68148e2977fc',
 '85c19c5e436590ad4beb6ddba948bb44',
 'c72e7b5bb50399a2e603843355266da6',
 '1be6c1b11b7ece0dbc74fd6bed3bae62',
 '76d94fbe397b7aa14f0a05c5a7dc40db',
 'da6746464e3869ffe6b773657591161e',
 'a909eb6cdc19d1dc6192b0f5932394a8',
 '31c814b5094c42dc600ebc1afaf3aec4',
 'dddcd94b0ecfb563529a1b265e690fef',
 '7b1ab2b028395728b7ce092344f967d3',
 '2566bcaac078ee1fc6f1744e42219bc3',
 '61f29aade065cc860f5f74078bf3e405',
 '9b1e6029e827f7bb02bf0d938ce9cf1b',
 'e92472d785f4a3d9fbddc8e10bcf6a0c',
 'ccd05b4af90b75dcd1d489585c067804',
 'cbe7092d023bf588d0537d9e060e3e4',
 'c5b9c76a44e974d9bedb47a1126e60f3',
 '7914aefbbe5ace32025bb19a5cf06a94',
 'f82b3edcb9b82a08d21202e44ccb40cf',
 '2a7c0293e5d2f0503a70f11d0559205f',
 'eb7473aa3f8fe7d77511903984043835',
 'c0eb0eedeab11a76bd0dcd252c375afd',
 '3eee3b70d6a7153db9f7146e74a43423',
 '34605eadab57f98ab94fe78b00d762d3',
 '816f72f2d74e5c0f2d469f15a87107e',
 '7f2d354f79b97b0b4246922f5f84e5f7',
 '6ec2191a2fdb883bbc834971c3a230cb',
 'e98cad99b03352857a0875dc01df3b5e',
 'ab9add7fd96cc7b33f3c8036daec422d',
 '49ad7d077b98d2f3d0623bd59a48c97a',
 '3f20334c3b4018200829e21cc3b8ea24',
 '403a9b38cca21e57d432d64644feb21c',
 '69190d0d97cd242b0dffae77b006a389',
 '8db58eee4b9342a4b4798f88eae794b7',
 '11d660c145d2a94f66660e405fe71709',
 'a3fc04b3f04f709c3fac892d5817e2ee',
 'c276b6dc2a03cddbefa93756c1f8e832',
 'a9fd8abfa741cd7ab7b01032bdf01928',
 '3b516a099e9265093a13a2f6d09c4b6',
 '645aec3af8a565a1ce76196580305653',
 'c2b6f5f7999ef55981278fb934306662',
 '202b9ba6d74f412a82d87834bc18dd47',
 '2211e2758c9e132bb4175cbe6bf2caba',
 '8b051dcb81541511b6a0f7fe136c3f54',
 'bd13055d02865ac2ced1298e286caba5',
 '77645e5a04107ad5f3db7cefaf59dbd5',
 '36946788df37e79fda1c89812eaa91d1',
 'e2f82f19d4a07d2dc676ac26243710c',
 '14e0052bd31697449a75bf2283e43508',
 '9ff2f1d582033c025e2dab8b9e1c6aac',
 'b9ee674b86c15e0efa1917aaaf3d7e98',
 '290900c0a93aaab2e3cd718b9d9b94f1',
 '646febd7f2d8edbf034c280b53b4758',
 'a4b6082afa5415bc7da7e72a22ab6fc9',
 'd7302fa9308fb73306fd880410b0b027',
 '6f31cb580f4410c5190114821c965d63',
 'ed5929856875acf96374e7af084b7b89',
 '4988ed7652377d13e31eba9bc6ea578',
 '8e2db044c642db140d76cf086252a930',
 '4569d960535dbfd697a38235c2eeccc6',
 'a87d77e141b0afc2a8be298c1405ce97',
 '93008cd63480b12f912a45063c92fcea',
 '3e139ce96849f8e76d53fa229a81bbbe',
 'c518711bf7c310e778f8025ef6ff2973',
 '38e2b97322ee453637b71da7b9d4dba8',
 'f08ee6e4e5b863508c5bf60359053120',
 '292c6bb22290ceb11c1c82d1d6111d36',
 'acde1fd1b674f699d6f4ef199a9ce347',
 '40eeffbb68222d9e3a7098cdd18f8879',
 'f683dc3160bc6be5800679e5d6760646',
 'e115d097d7ff6a107fe1e2e32c74881d',
 'e2f1f662c446e88924abc95143e92b0a',
 'd7b58eb366ee247dfafe1b58fba40525',
 'e81a85b19b9b0e52ee09fba8e58b8d99',
 '67f46876ccb48a0b4462ddb062a56250',
 '856dce35557af051d6a11d09eb49bbc7',
 '7a4f7d8c3b9aa1f0798ea36d14d61e22',
 'b6b6e9032eef58c20b3ef1868f1ce40',
 'ba8e745478de3435bcdbb1759891fbf6',
 '95f7a909e6f53e0628a56ecc4ec92d13',
 '461db950594f9c6dfbdafbae33284ae',
 'a83bd568d95664318703f24a3ae418ba',
 'd2cf82bfcf0e5199a66a47c9826e7356',
 'bedc5edc27b3e2ae33530146a67a18d9',
 'b97d075bdb2e45cb0a2820fd55c40b8f',
 'fff35e77040a1508d17d58f236c35e4b',
 '3bc5bedfd3b63a3d67286f8cd3cc49b5',
 '89cc78783cada5d37c54874eead08397',
 '647af0b3b60b7e0c8e79f4767ea763c0',
 'ecb738b2095981db44bd0a9c75b9479f',
 'd2b4ca4bb253a600546f32ecbab23fee',
 'b7a8ef3417f453cbd1d1e287532b130a',
 '1b794351f748c67d9903c518228e6abd',
 'fee3ac2a69e002488cc25d23114b0ad',
 '3685653b305a2670a3076101d80f68e1',
 'ac10637cb5613a8b160adc696581ac46',
 'c1ea208cc385c3d97289dc0457c357fb',
 'a1aef3462a02a2d7a94fc372159f3a2',
 'a09ba0fff28945d46f71684b15c68f82',
 'c03883c16106673a1692d11a58cc6e4e',
 '21f14bbf4200fb890ba103e0cebe2d0a',
 '838ab7a7ce7fce818aa6b810814c1cec',
 '6847ac0fd53495c9aa48e7a7097a7c4e',
 '5ed07d54714481e6a073fe829f727f3a',
 'df5064da07e45088c99835fb1512d515',
 'cf14186fda7b6faac4ba596a770cfdf5',
 '5de42b8c2bb7b8acdf3d051d943fb8df',
 'de7b01128082013a2f347cbe3ab7a843',
 'e7e870a0a689f991f870ae45a847badf',
 'e590bfc9cdd893f6a73f256c039079ee',
 '2177afbfd023258db22d4f1587d8001',
 'f82f4d89b23e519f3522c552fc2bf06e',
 '3a1095affa3d8a135599777af2b7005a',
 'ff91be1709bee31ad754aa1f0d49e3f3',
 '19a1e8764dc0076f6e8502c0afe4c567',
 '5c2ac5510c05d4dedf3eda3231509e4a',
 '5a312605bc978a001c74c6f16b751f8a',
 'cc66ce2dfe1d9097c9e899b57d298b2c',
 '523632e0c2385b1aeb06965844c9b955',
 '8ee3d7a474383b736416b73664acc999',
 '23b76a43b3c670d733dd1ce31d6c6f20',
 '40502e676682d22fc627910037e68276',
 '656ed160baa9e46affa1bd0506009e1c',
 'c5d865e3213ff224bc04b7f7b5928c8e',
 '1a5a5ff661ee7b72683365e00e3bbc25',
 'ebc216f958ecfef8b6e5bed4770a3a79',
 '6b8083d4232e6bc0b3c53c9fa5bb9d6e',
 '29efa957998210d634e73102e97d3bc2',
 '5d3e93f534c8058921600ef14da55d11',
 '93143081fdc1997fcf71eedb48bb23c4',
 'd0e9c3576f0d978fb58bd7725f655e31',
 '6b8fa8bb7118ac7b5a901404eb3110d3',
 '2cdb5c95ce7c71655d26ed02438ccc3',
 '360d0b0d0bf1a8112f9bee04350ac44b',
 '9a396d5e80801c6963f2da7644cabb9b',
 'f46b988ce96cd7de25cbad6119a8ac50',
 'f0bbccf84b9c6ac768bb110b89974334',
 'e2ea96994574cac98edd333c13598c46',
 'b7e1efbf5371111618be79d6c12a574e',
 'a3741a0727e095a6a2007c47a402b61e',
 '232e87e239e93bdb49671e244db5f6d0',
 '5f10fbdecb676febad3c3f1d9ddab6e4',
 '6ec737bb3d26643629c37694bd57bfa9',
 'a8d13210c76f7a7a6cb3764b56f397e9',
 '1098f09a3aa1e3488765242d53ebf436',
 'd4d1076e270f84cc38fcce80acbca4ab',
 'ce9d3800727efd526f743c14b4506ffe',
 'ed75ec9e1645aec7e68cdede0d83acce',
 '97aa55374e2d6cc98614bb74ff8cba8e',
 'd79047de1408527efeca9bc00259d92c',
 'f116864d9c1e65b014002d787b71be17',
 'a0572f48e774b09b65ffd40f37135b51',
 '825dbc676dbd0b3370e0c7719a63a425',
 '701d8c8f63a6f249d0fb2554efc94686',
 '7cf17bd7f749682003635ee9135ab832',
 'a22af0bb1ed1e47f9f285f7f6a766d6',
 'dc5a479bafd3f74020a241662175b57d',
 '7f28b14639e1b9ca197e08dca4bf4e3',
 '50996a518d7453801fbc2288b26bcd69',
 'c65e07ec3d9c631a4b5e268b9d5d5009',
 '46d50398dc9b8dba907eb4a2699e388f',
 'b549dc815a1841ae4db2112c809a9689',
 'e2a7883609fd42bdc9d6a56af23db50f',
 'bae93ebef76efa36f03f0f641573c060',
 '9f9778f0155ce7027e26de2a076ee6f5',
 'fbfea65ab63343fbeeca4f1199e6e0e0',
 'eb3855d4ad37bd06d454977da4897eb4',
 '71272abcf165535abed0bd595b0e9b63',
 'ca4b233183b3a8119d721eaa6d699d6a',
 '1b2910fba3d00922c80c8c3f0c1b721e',
 '140cb04099c769d03cb90ec25e45f88',
 'c6ad6a84d2788eb5b07a37a0684ef6e7',
 'b8dc3e68f8449b1da7e37e00b3f9f4fe',
 'c8203a41c64794261cf09ee68c1f2940',
 '71cd609ade447c8828c1f3218b69bda7',
 '37e13adb975930781fe9b69cd1206f43',
 '36f2e0ccc04f257f2b68bd3b6126e52c',
 '37db4e97ba8b9883f7bee6a5509d6de4',
 '297cf189d4ce1deb72cba1127038e5d1',
 '25809bf822af0616ed596b73ea7fbf8c',
 '4a09800fac28b5b0262fdabd678d7898',
 'f2c27efb9dff3cfcfd46bff4a3b09746',
 'a53d195bde06b39edf10ed4e5b5bed23',
 'bd630f8e35d9e3f9ddef492c02ba182',
 '99d929a3dbaec5cfab585347844c524d',
 'c59bd41ec54b844fe847d4f6e34b342c',
 'a7db49f472ebbfaa4ed9320fd882cd12',
 '93dfed1b00e51cdf8b8a97a7e593b740',
 '8401179da97b9cd0ce31f7013160c998',
 'bb6836c790e84c9575cd53b0c3272f68',
 'b313a7f46c89a4cae0b8ec8293c6e944',
 '366a9b110abb099081ed7363b41829c2',
 '5bf938c26fd17d608c07ca6ccabb2b0b',
 '521e7057b110eaedf6073ef4d15a667a',
 '6eab4042f4551f860ff05480818ac23b',
 '2b60501e90f9314addaa87bbbb8345fd',
 '10a49809e53fcae0233beb77036d15f7',
 '813d3b44cd75e28f3ad3ed591f5ab915',
 'aed3fb9593cd6b60d68e6527dee8e3f3',
 '8c2ad6ffec9759b78fd469369821b635',
 'f64394782c2c9f46ec37c5976bf3eada',
 'ccadabd579e8d6b0d870da18fa015b8d',
 '87a598e2f229366b9f425abe6dcf1093',
 '731846c5b168415a1298071c252381a4',
 'aceea1750b1fcabb624df577fdc9fdad',
 '16895cf981140a0c7b9c6228a060cb68',
 'ac1245caad53434add31917ab35c83fa',
 '765dbaa3a592d3af3e7d0a0feac0e7d5',
 '26f176fd3f6b6cccbb1e2acc38a68f3d',
 '283b82dd8720eb4df55e354716c4e3ac',
 '33ccb3b996ba28909eb3df5dd6bab261',
 'ca7d31570e0c293156359cfb8c2b6c1a',
 'f811851e5d1ef86c8cf33e3190625f13',
 'b7759ffafed67861a19bf5e39ff8df45',
 'cb16a11ba6d565d67c1b53d052ed69a2',
 'de805e86dfd4a31a19695f5b3b01f519',
 '82181c4d41b17ced08f8be15f490b553',
 '16f8186eb2af8a6298d78dc35908828e',
 'ccac7358fb921ec75b0b50c7f14eeb38',
 'de5777767d1db255b17d54c3b7c021ba',
 '158a58aa08f9ba03d53868c3b2f9a8aa',
 '75a78c7946f25b541eadd7aacf701feb',
 'ec5d2e46cd9950ded3c89ff1f57d5688',
 'd09fc261467bb3a618981dbf9bdd1f7e',
 '3d08bf275a2849585b9e2b86b3c659ec',
 '87293f160c7873a93d064a0aa68e4889',
 '1473938558d42fc6ea10cf62e4eb3ccb',
 'd14b2187872b7c4ac45108be2f23ffd5',
 '4841b524cedac7ff774de4a7650fd463',
 'd661a4fc9372af3edc85235e496946c7',
 '2ba013ed8a9aa7e5091a40d8b17ee097',
 '17b4b5a9cbdb58ff462ba607dab0bd43',
 '93210142c63fcf587f17a562712cfea0',
 'cf1bb6782d12f870dc1f496122aede20']

## 3) Generate a path and key for the coordinates

In [13]:
def create_mapping_file_entry(rootdir, netcdf_folder, file_suffix='accum.nc'):

    # get zipfolder items
    items = os.listdir(os.path.join(rootdir, netcdf_folder)) # folder items

    # identify the target file
    fpath = [f for f in items if f.endswith(file_suffix)][0]

    # read nc
    file2read = nc.Dataset(os.path.join(rootdir, netcdf_folder, fpath), 'r')

    # generate the dictionary
    nc_coord = {
        'hash': eachfol,
        'fpath': os.path.join(root_dir, eachfol, fpath),
        'longitude': file2read['longitude'][:][0],
        'latitude': file2read['latitude'][:][0]}

    return(nc_coord)


# placeholder
mapping_file_entries = dict()

# iterate through each folder
for ind, eachfol in enumerate(fold):
    mapping_file_entries[ind]=create_mapping_file_entry(rootdir=root_dir,
                                                        netcdf_folder = eachfol,
                                                        file_suffix='accum.nc')

In [14]:
pd.DataFrame.from_dict(mapping_file_entries).T

,hash,fpath,longitude,latitude
0,1f34aeeee050084abd5eb16b010f8c5b,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
1,f294553b45c604483ac76e0ead287015,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
2,55779745d3fd682f6f077107164015a7,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
3,d7f8a1c12c7c27547651dc84e57bd88d,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
4,5e53c89f63764ce3aadc278055bb20b8,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
...,...,...,...,...
283,d661a4fc9372af3edc85235e496946c7,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
284,2ba013ed8a9aa7e5091a40d8b17ee097,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
285,17b4b5a9cbdb58ff462ba607dab0bd43,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
286,93210142c63fcf587f17a562712cfea0,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63
287,cf1bb6782d12f870dc1f496122aede20,/Users/jphuong/Documents/OHDSI GIS/corrupted M...,33.01,-2.63

## 4) extract the values

In [15]:
instance = 2 # gather from the first folder
print(os.path.join(root_dir, fold[instance]))

# get zipfolder items
tmp = os.listdir(os.path.join(root_dir, fold[instance])) # first folder items

tmp

/Users/jphuong/Documents/OHDSI GIS/corrupted Monthly temp_Precip_Magu_1992-2015/55779745d3fd682f6f077107164015a7

['data_stream-oper_stepType-accum.nc', 'data_stream-oper_stepType-instant.nc']

In [16]:
# identify the target file
fpath = [f for f in tmp if f.endswith('accum.nc')][0]
fpath

'data_stream-oper_stepType-accum.nc'

In [17]:
# read nc

# netCDF4 method
file2read = nc.Dataset(os.path.join(root_dir, fold[instance], fpath), 'r')

#xarray method
f2r = xr.open_dataset(os.path.join(root_dir, fold[instance], fpath))

file2read

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    GRIB_centre: ecmf
    GRIB_centreDescription: European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre: 0
    Conventions: CF-1.7
    institution: European Centre for Medium-Range Weather Forecasts
    history: 2025-10-10T15:37 GRIB to CDM+CF via cfgrib-0.9.15.0/ecCodes-2.42.0 with {"source": "tmpm16c2z_9/data.grib", "filter_by_keys": {"stream": ["oper"], "stepType": ["accum"]}, "encode_cf": ["parameter", "time", "geography", "vertical"]}
    dimensions(sizes): valid_time(672), latitude(1), longitude(1)
    variables(dimensions): int64 number(), int64 valid_time(valid_time), float64 latitude(latitude), float64 longitude(longitude), <class 'str'> expver(valid_time), float32 tp(valid_time, latitude, longitude)
    groups:

In [18]:
file2read.variables.keys()

dict_keys(['number', 'valid_time', 'latitude', 'longitude', 'expver', 'tp'])

In [19]:
f2r.variables.keys()

KeysView(Frozen({'number': <xarray.Variable ()> Size: 8B
[1 values with dtype=int64]
Attributes:
    long_name:      ensemble member numerical id
    units:          1
    standard_name:  realization, 'valid_time': <xarray.IndexVariable 'valid_time' (valid_time: 672)> Size: 5kB
array(['2015-02-01T00:00:00.000000000', '2015-02-01T01:00:00.000000000',
       '2015-02-01T02:00:00.000000000', ..., '2015-02-28T21:00:00.000000000',
       '2015-02-28T22:00:00.000000000', '2015-02-28T23:00:00.000000000'],
      dtype='datetime64[ns]')
Attributes:
    long_name:      time
    standard_name:  time, 'latitude': <xarray.IndexVariable 'latitude' (latitude: 1)> Size: 8B
array([-2.63])
Attributes:
    units:          degrees_north
    standard_name:  latitude
    long_name:      latitude, 'longitude': <xarray.IndexVariable 'longitude' (longitude: 1)> Size: 8B
array([33.01])
Attributes:
    units:          degrees_east
    standard_name:  longitude
    long_name:      longitude, 'expver': <xarray.Variable (valid_time: 672)> Size: 11kB
[672 values with dtype=<U4], 'tp': <xarray.Variable (valid_time: 672, latitude: 1, longitude: 1)> Size: 3kB
[672 values with dtype=float32]
Attributes: (12/32)
    GRIB_paramId:                             228
    GRIB_dataType:                            fc
    GRIB_numberOfPoints:                      1
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            accum
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               m
    long_name:                                Total precipitation
    units:                                    m
    standard_name:                            unknown
    GRIB_surface:                             0.0}))

## Function to test the netcdf object for the sample size for the temporal window

# standard parameter 200 units

In [20]:
# generate table

test = dict()

test[fold[instance]] = pd.DataFrame.from_dict({
    #'valid_time': file2read['valid_time'][:],
    'valid_time_xr': pd.Series(f2r.indexes['valid_time']),
    'total_precip': pd.Series(map(lambda x: x[0][0], file2read['tp'][:])),
    'expver':file2read['expver'][:],
    }, orient='columns')

# inspect
test[fold[instance]]

          valid_time_xr  total_precip expver
0   2015-02-01 00:00:00  0.000000e+00   0001
1   2015-02-01 01:00:00  0.000000e+00   0001
2   2015-02-01 02:00:00  0.000000e+00   0001
3   2015-02-01 03:00:00  0.000000e+00   0001
4   2015-02-01 04:00:00  0.000000e+00   0001
..                  ...           ...    ...
667 2015-02-28 19:00:00  0.000000e+00   0001
668 2015-02-28 20:00:00  0.000000e+00   0001
669 2015-02-28 21:00:00  0.000000e+00   0001
670 2015-02-28 22:00:00  0.000000e+00   0001
671 2015-02-28 23:00:00  4.959087e-07   0001

[672 rows x 3 columns]

In [61]:
def temporality_check(obj, time_field_name):
    """
    obj : dataframe
    time_field_name : str

    --
    return
    """

    # annual
    if obj.shape[0] == obj[time_field_name]\
        .apply(lambda x: str(x.year)).unique().shape[0]:
        return('annual')

    # monthyearly
    if obj.shape[0] == obj[time_field_name]\
        .apply(lambda x: '-'.join([str(x.year), str(x.month)])).unique().shape[0]:
        return('monthyearly')

    # monthyearly
    if obj.shape[0] == obj[time_field_name]\
        .apply(lambda x: str(x.month)).unique().shape[0]:
        return('monthly')
        
    # daily
    if obj.shape[0] == obj[time_field_name]\
        .apply(lambda x: '-'.join([str(x.year), str(x.month), str(x.day)])).unique().shape[0]:
        return('daily')
    
    # dailyhourly
    if obj.shape[0] == obj[time_field_name]\
        .apply(lambda x: ' '.join([
            '-'.join([str(x.year), str(x.month), str(x.day)]), str(x.hour)])).unique().shape[0]:
        return('dailyhourly')

    # hourly
    if obj.shape[0] == obj[time_field_name]\
        .apply(lambda x: str(x.hour)).unique().shape[0]:
        return('hourly')

    # minutely
    if obj.shape[0] == obj[time_field_name]\
        .apply(lambda x: ' '.join([
            '-'.join([str(x.year), str(x.month), str(x.day)]), 
            ':'.join([str(x.hour), str(x.minute)])])).unique().shape[0]:
        return('minutely')

def temporal_extent(obj, time_field_name):
    """
    obj : dataframe
    time_field_name : str

    --
    return
    """

    return([obj[time_field_name].min(), obj[time_field_name].max(), obj[time_field_name].nunique()])

In [57]:
temporality_check(obj=test[fold[instance]], time_field_name='valid_time_xr')

'dailyhourly'

In [62]:
temporal_extent(obj=test[fold[instance]], time_field_name='valid_time_xr')

[Timestamp('2015-02-01 00:00:00'), Timestamp('2015-02-28 23:00:00'), 672]

In [39]:
# annual
test[fold[instance]].shape[0] == test[fold[instance]].valid_time_xr\
    .apply(lambda x: str(x.year)).unique().shape[0]

# monthyearly
test[fold[instance]].shape[0] == test[fold[instance]].valid_time_xr\
    .apply(lambda x: '-'.join([str(x.year), str(x.month)])).unique().shape[0]

# daily
test[fold[instance]].shape[0] == test[fold[instance]].valid_time_xr\
    .apply(lambda x: '-'.join([str(x.year), str(x.month), str(x.day)])).unique().shapep[0]

# hourly
test[fold[instance]].valid_time_xr\
    .apply(lambda x: ' '.join([
        '-'.join([str(x.year), str(x.month), str(x.day)]), 
        str(x.hour)])).unique().shape[0]

False

In [38]:
# hourly

False

In [46]:
# annual
#test[fold[instance]].shape[0] == 

test[fold[instance]].valid_time_xr\
    .apply(lambda x: ' '.join([
        '-'.join([str(x.year), str(x.month), str(x.day)]), 
        str(x.hour)])).unique().shape[0]

672

In [44]:
# date
test[fold[instance]].valid_time_xr.apply(lambda x: '-'.join([str(x.year), str(x.month), str(x.day)])).unique()

array(['2015-2-1', '2015-2-2', '2015-2-3', '2015-2-4', '2015-2-5',
       '2015-2-6', '2015-2-7', '2015-2-8', '2015-2-9', '2015-2-10',
       '2015-2-11', '2015-2-12', '2015-2-13', '2015-2-14', '2015-2-15',
       '2015-2-16', '2015-2-17', '2015-2-18', '2015-2-19', '2015-2-20',
       '2015-2-21', '2015-2-22', '2015-2-23', '2015-2-24', '2015-2-25',
       '2015-2-26', '2015-2-27', '2015-2-28'], dtype=object)

In [24]:
test[fold[instance]].head(50)

         valid_time_xr  total_precip expver
0  2015-02-01 00:00:00  0.000000e+00   0001
1  2015-02-01 01:00:00  0.000000e+00   0001
2  2015-02-01 02:00:00  0.000000e+00   0001
3  2015-02-01 03:00:00  0.000000e+00   0001
4  2015-02-01 04:00:00  0.000000e+00   0001
5  2015-02-01 05:00:00  0.000000e+00   0001
6  2015-02-01 06:00:00  0.000000e+00   0001
7  2015-02-01 07:00:00  0.000000e+00   0001
8  2015-02-01 08:00:00  1.449583e-06   0001
9  2015-02-01 09:00:00  1.308437e-05   0001
10 2015-02-01 10:00:00  1.998895e-05   0001
11 2015-02-01 11:00:00  2.942971e-05   0001
12 2015-02-01 12:00:00  1.356121e-05   0001
13 2015-02-01 13:00:00  8.563984e-04   0001
14 2015-02-01 14:00:00  7.438622e-07   0001
15 2015-02-01 15:00:00  0.000000e+00   0001
16 2015-02-01 16:00:00  0.000000e+00   0001
17 2015-02-01 17:00:00  0.000000e+00   0001
18 2015-02-01 18:00:00  0.000000e+00   0001
19 2015-02-01 19:00:00  0.000000e+00   0001
20 2015-02-01 20:00:00  0.000000e+00   0001
21 2015-02-01 21:00:00  0.000000e+00   0001
22 2015-02-01 22:00:00  0.000000e+00   0001
23 2015-02-01 23:00:00  0.000000e+00   0001
24 2015-02-02 00:00:00  0.000000e+00   0001
25 2015-02-02 01:00:00  0.000000e+00   0001
26 2015-02-02 02:00:00  0.000000e+00   0001
27 2015-02-02 03:00:00  0.000000e+00   0001
28 2015-02-02 04:00:00  2.098121e-07   0001
29 2015-02-02 05:00:00  4.196242e-07   0001
30 2015-02-02 06:00:00  2.098121e-07   0001
31 2015-02-02 07:00:00  0.000000e+00   0001
32 2015-02-02 08:00:00  4.959112e-06   0001
33 2015-02-02 09:00:00  5.350179e-05   0001
34 2015-02-02 10:00:00  1.693721e-05   0001
35 2015-02-02 11:00:00  1.037596e-05   0001
36 2015-02-02 12:00:00  1.184461e-05   0001
37 2015-02-02 13:00:00  3.166186e-06   0001
38 2015-02-02 14:00:00  2.479534e-07   0001
39 2015-02-02 15:00:00  0.000000e+00   0001
40 2015-02-02 16:00:00  0.000000e+00   0001
41 2015-02-02 17:00:00  0.000000e+00   0001
42 2015-02-02 18:00:00  0.000000e+00   0001
43 2015-02-02 19:00:00  0.000000e+00   0001
44 2015-02-02 20:00:00  0.000000e+00   0001
45 2015-02-02 21:00:00  0.000000e+00   0001
46 2015-02-02 22:00:00  0.000000e+00   0001
47 2015-02-02 23:00:00  0.000000e+00   0001
48 2015-02-03 00:00:00  0.000000e+00   0001
49 2015-02-03 01:00:00  2.161023e-05   0001

## 5) look at the instant data

In [305]:
# identify the target file
fpath = [f for f in tmp if f.endswith('instant.nc')][0]
fpath

file2read_inst = nc.Dataset(os.path.join(root_dir, fold[instance], fpath), 'r')
file2read_inst

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    GRIB_centre: ecmf
    GRIB_centreDescription: European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre: 0
    Conventions: CF-1.7
    institution: European Centre for Medium-Range Weather Forecasts
    history: 2025-10-10T15:37 GRIB to CDM+CF via cfgrib-0.9.15.0/ecCodes-2.42.0 with {"source": "tmpm16c2z_9/data.grib", "filter_by_keys": {"stream": ["oper"], "stepType": ["instant"]}, "encode_cf": ["parameter", "time", "geography", "vertical"]}
    dimensions(sizes): valid_time(672), latitude(1), longitude(1)
    variables(dimensions): int64 number(), int64 valid_time(valid_time), float64 latitude(latitude), float64 longitude(longitude), <class 'str'> expver(valid_time), float32 t2m(valid_time, latitude, longitude)
    groups:

In [315]:
file2read_inst.variables.keys()

dict_keys(['number', 'valid_time', 'latitude', 'longitude', 'expver', 't2m'])

In [313]:
# generate table

test = dict()

test[fold[instance]] = pd.DataFrame.from_dict({
    #'valid_time': file2read['valid_time'][:],
    'valid_time_xr': pd.Series(f2r.indexes['valid_time']),
    'T2M': pd.Series(map(lambda x: x[0][0], file2read_inst['t2m'][:])),
    'expver':file2read['expver'][:],
    }, orient='columns')

# inspect
test[fold[instance]]

          valid_time_xr         T2M expver
0   2015-02-01 00:00:00  294.765381   0001
1   2015-02-01 01:00:00  294.318115   0001
2   2015-02-01 02:00:00  294.134277   0001
3   2015-02-01 03:00:00  295.360107   0001
4   2015-02-01 04:00:00  295.268066   0001
..                  ...         ...    ...
667 2015-02-28 19:00:00  297.096191   0001
668 2015-02-28 20:00:00  296.993408   0001
669 2015-02-28 21:00:00  296.100342   0001
670 2015-02-28 22:00:00  294.226807   0001
671 2015-02-28 23:00:00  293.781738   0001

[672 rows x 3 columns]

## attic

In [217]:
#file2read.variables()
file2read.variables.keys()

KeysView(Frozen({'number': <xarray.Variable ()> Size: 8B
[1 values with dtype=int64]
Attributes:
    long_name:      ensemble member numerical id
    units:          1
    standard_name:  realization, 'valid_time': <xarray.IndexVariable 'valid_time' (valid_time: 672)> Size: 5kB
array(['2015-02-01T00:00:00.000000000', '2015-02-01T01:00:00.000000000',
       '2015-02-01T02:00:00.000000000', ..., '2015-02-28T21:00:00.000000000',
       '2015-02-28T22:00:00.000000000', '2015-02-28T23:00:00.000000000'],
      dtype='datetime64[ns]')
Attributes:
    long_name:      time
    standard_name:  time, 'latitude': <xarray.IndexVariable 'latitude' (latitude: 1)> Size: 8B
array([-2.63])
Attributes:
    units:          degrees_north
    standard_name:  latitude
    long_name:      latitude, 'longitude': <xarray.IndexVariable 'longitude' (longitude: 1)> Size: 8B
array([33.01])
Attributes:
    units:          degrees_east
    standard_name:  longitude
    long_name:      longitude, 'expver': <xarray.Variable (valid_time: 672)> Size: 11kB
[672 values with dtype=<U4], 'tp': <xarray.Variable (valid_time: 672, latitude: 1, longitude: 1)> Size: 3kB
[672 values with dtype=float32]
Attributes: (12/32)
    GRIB_paramId:                             228
    GRIB_dataType:                            fc
    GRIB_numberOfPoints:                      1
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            accum
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               m
    long_name:                                Total precipitation
    units:                                    m
    standard_name:                            unknown
    GRIB_surface:                             0.0}))

In [220]:
# generate the dictionary
nc_coord = {
    'fpath': os.path.join(root_dir, eachfol, fpath),
    'longitude': file2read['longitude'][:][0],
    'latitude': file2read['latitude'][:][0]}
nc_coord

{'fpath': '/Users/jphuong/Documents/OHDSI GIS/Monthly temp_Precip_Magu_1992-2015/cf1bb6782d12f870dc1f496122aede20/data_stream-oper_stepType-accum.nc',
 'longitude': <xarray.DataArray 'longitude' ()> Size: 8B
 array(33.01)
 Coordinates:
     number     int64 8B ...
     longitude  float64 8B 33.01
 Attributes:
     units:          degrees_east
     standard_name:  longitude
     long_name:      longitude,
 'latitude': <xarray.DataArray 'latitude' ()> Size: 8B
 array(-2.63)
 Coordinates:
     number    int64 8B ...
     latitude  float64 8B -2.63
 Attributes:
     units:          degrees_north
     standard_name:  latitude
     long_name:      latitude}